v2: implement PrintPluginName
This doesn't work currently, because github.com/thaJeztah/mod-migrate "v2"
is not the same as github.com/thaJeztah/mod-migrate "v1"; they're separate
modules:

	github.com/thaJeztah/mod-migrate/v2/pkg/foo
	github.com/thaJeztah/mod-migrate/pkg/foo

And compile therefore fails:

    # github.com/thaJeztah/mod-migrate/v2
    ./main.go:23:18: cannot use p (variable of type *plugin.Plugin) as Plugin value in argument to PrintPluginName: *plugin.Plugin does not implement Plugin (wrong type for method Hello)
            have Hello() *"github.com/thaJeztah/mod-migrate/pkg/foo".Hello
            want Hello() *"github.com/thaJeztah/mod-migrate/v2/pkg/foo".Hello

Signed-off-by: Sebastiaan van Stijn <github@gone.nl>